
import { useScrollReveal } from '../hooks/useScrollReveal';

interface FinalCTAProps {
  darkMode: boolean;
}

const benefits = [
  'RFQ emails are automatically detected and labeled — no more inbox searching',
  'PDF attachments are parsed and data is extracted in seconds — no more manual copy-paste',
  'Professional quotation responses are generated by AI — no more starting from scratch',
  'You respond faster than your competition — and win more business',
];

const FinalCTA: React.FC<FinalCTAProps> = ({ darkMode }) => {
  const { ref, revealed } = useScrollReveal();

  return (
    <section className={`py-24 lg:py-32 relative overflow-hidden ${darkMode ? 'bg-[#080c1e]' : 'bg-gray-50/80'}`}>
      {/* Background */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[600px] rounded-full blur-3xl opacity-20"
          style={{ background: 'radial-gradient(ellipse, rgba(59,130,246,0.4) 0%, rgba(29,78,216,0.2) 50%, transparent 100%)' }}
        />
        <div className={`absolute inset-0 opacity-[0.02]`}
          style={{
            backgroundImage: `linear-gradient(rgba(59,130,246,0.8) 1px, transparent 1px), linear-gradient(90deg, rgba(59,130,246,0.8) 1px, transparent 1px)`,
            backgroundSize: '60px 60px'
          }}
        />
      </div>

      <div ref={ref} className={`section-reveal ${revealed ? 'revealed' : ''} relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center`}>
        <span className={`inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold mb-6 border ${
          darkMode ? 'bg-blue-950/60 border-blue-700/50 text-blue-300' : 'bg-blue-50 border-blue-200 text-blue-700'
        }`}>
          Get Started Today — It's Free
        </span>

        <h2 className={`text-3xl sm:text-4xl lg:text-5xl xl:text-6xl font-extrabold tracking-tight mb-6 leading-[1.1] ${darkMode ? 'text-white' : 'text-gray-950'}`}>
          Stop Losing Deals to{' '}
          <span className="gradient-text">Slow RFQ Responses</span>
        </h2>

        <p className={`text-lg sm:text-xl leading-relaxed mb-10 max-w-2xl mx-auto ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
          Every hour you spend manually processing an RFQ is an hour your competitor is using to close the deal.
          RFQ AutoPilot automates the entire workflow — from inbox to quotation.
        </p>

        {/* Benefits */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-10 text-left max-w-2xl mx-auto">
          {benefits.map((benefit, i) => (
            <div key={i} className={`flex items-start gap-3 p-4 rounded-xl border ${
              darkMode ? 'bg-blue-950/20 border-blue-900/30' : 'bg-white border-gray-200/60'
            }`}>
              <svg className="w-5 h-5 text-emerald-500 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"/>
              </svg>
              <p className={`text-sm leading-snug ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>{benefit}</p>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="flex items-center justify-center mb-8">
          <a
            href="https://chromewebstore.google.com/detail/rfq-autopilot/akeilceddenpdgocpcmoiemfhpaofebl"
            target="_blank"
            rel="noopener noreferrer"
            className="group flex items-center gap-3 px-8 py-4 rounded-2xl text-lg font-bold text-white gradient-brand btn-glow transition-all duration-300 hover:scale-105 animate-gradient-shift shadow-2xl shadow-blue-500/30"
          >
            <svg className="w-5 h-5 group-hover:rotate-12 transition-transform duration-300" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 14H9V8h2v8zm4 0h-2V8h2v8z"/>
            </svg>
            Add to Chrome — It's Free
          </a>
        </div>

        {/* Trust mini bar */}
        <div className={`flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm ${darkMode ? 'text-gray-500' : 'text-gray-500'}`}>
          <span>🆓 Free plan includes 30 RFQs/month</span>
          <span>·</span>
          <span>No credit card required</span>
          <span>·</span>
          <span>Works with Gmail & Outlook</span>
        </div>
      </div>
    </section>
  );
};

export default FinalCTA;
